// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

bool pushButton;
char* letters[] = {
".-", "-...", "-.-.", "-..", ".", "..-.", "--.", "....", "..", // A-I
".---", "-.-", ".-..", "--", "-.", "---", ".--.", "--.-", ".-.", // J-R 
"...", "-", "..-", "...-", ".--", "-..-", "-.--", "--.." // S-Z
};
const byte numChars = 32;
char receivedChars[numChars];   
bool newData = false;

void onPushButtonChange();
void longBeep();
void shortBeep();






void initProperties(){

  ArduinoCloud.addProperty(pushButton, READWRITE, ON_CHANGE, onPushButtonChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
